-- Add detailed profile columns for abogados
ALTER TABLE abogados
  ADD COLUMN IF NOT EXISTS formacion TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS experiencia TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS docencia TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS publicaciones TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS distinciones TEXT DEFAULT NULL;
