-- Seed script: ejemplo de abogados para mostrar en el sitio
-- Ejecutar en MySQL / phpMyAdmin: SOURCE path/to/seed_abogados_example.sql;

INSERT INTO abogados (nombre, correo, celular, foto_carnet, foto_full, descripcion, area_practica, formacion, experiencia, docencia, publicaciones, distinciones, facebook, instagram, linkedin, twitter, whatsapp, cargo, destacado, fecha_creacion)
VALUES
('Alfonso Moisés Jiménez Pintado', 'alfonso.jimenez@bufete.com', '+593998877661', '/uploads/abogados/alfonso_carnet.jpg', '/uploads/abogados/alfonso_full.jpg', 'Socio Fundador con amplia experiencia en derecho penal y procesal.', 'Derecho penal, Defensa criminal', '• Abogado – Universidad de Guayaquil\n• Candidato a Doctor (PhD) – Universidad Católica Andrés Bello\n• Máster en Derecho Procesal Constitucional – UNEMI\n• Máster en Derecho Procesal Penal – UNEMI\n• Máster en Política Criminal y Derecho Penitenciario – Universidad de Guayaquil\n• Máster en Criminología, Victimología y Delincuencia – Universidad Internacional de Valencia', 'Ha desempeñado funciones relevantes en defensa de casos complejos y asesoría a altos cargos públicos.', 'Profesor universitario en pregrado y posgrado desde 2008.', 'Artículos y ponencias en materia penal y procesal.', 'Premios a la trayectoria profesional.', 'https://facebook.com/alfonsocaso', '', 'https://linkedin.com/in/alfonsojimenez', '', 'https://wa.me/593998877661', 'Socio Fundador', 1, NOW()),

('Débora Victoria Mora Mora', 'debora.mora@bufete.com', '+593998877662', '/uploads/abogados/debora_carnet.jpg', '/uploads/abogados/debora_full.jpg', 'Presidenta de la firma, especializada en derecho corporativo y gestión institucional.', 'Derecho corporativo, Asesoría institucional', '• Abogada – Universidad Bolivariana del Ecuador', 'Amplia experiencia en dirección institucional y asesoría legal corporativa.', '', '', '', '', '', 'https://linkedin.com/in/deboramora', '', 'https://wa.me/593998877662', 'Presidenta', 0, NOW()),

('Silvia Patricia Jiménez Herrera', 'silvia.jimenez@bufete.com', '+593998877663', '/uploads/abogados/silvia_carnet.jpg', '/uploads/abogados/silvia_full.jpg', 'Gerente del Departamento Jurídico y Financiero, experta en gestión y procesos.', 'Gestión jurídica, Finanzas', '• Ingeniera Comercial – Universidad Laica Vicente Rocafuerte de Guayaquil', 'Responsable de la gestión administrativa y financiera del despacho.', '', '', '', '', '', '', '', '', 'Gerente del Departamento Jurídico', 0, NOW()),

('Karen Helen Jácome Santillán', 'karen.jacome@bufete.com', '+593998877664', '/uploads/abogados/karen_carnet.jpg', '/uploads/abogados/karen_full.jpg', 'Responsable de Comunicación Social e Imagen Corporativa.', 'Comunicación e imagen', '• Licenciada en Periodismo – Universidad Laica Vicente Rocafuerte de Guayaquil\n• Certificación en Capital Humano – SECAP\n• Máster en Gestión del Talento Humano – UNEMI', 'Lidera estrategias de comunicación y marca institucional.', '', '', '', '', '', '', '', '', 'Responsable Comunicación', 0, NOW()),

('María Fernanda Ibarra Sevillano', 'maria.ibarra@bufete.com', '+593998877665', '/uploads/abogados/maria_carnet.jpg', '/uploads/abogados/maria_full.jpg', 'Abogada con formación doctoral y experiencia en derecho penal.', 'Derecho penal', '• Abogada – Universidad de Guayaquil\n• Doctorado – Universidad César Vallejo, Perú\n• Máster en Derecho Procesal Penal – UNEMI', 'Experiencia en litigio penal y defensa penal especializada.', '', '', '', '', '', '', '', '', 'Abogada', 0, NOW()),

('Joel Jesús Navarrete García', 'joel.navarrete@bufete.com', '+593998877666', '/uploads/abogados/joel_carnet.jpg', '/uploads/abogados/joel_full.jpg', 'Abogado con maestría en derecho procesal.', 'Derecho procesal', '• Abogado – Universidad Laica Vicente Rocafuerte de Guayaquil\n• Máster en Derecho Procesal – Universidad Laica Vicente Rocafuerte de Guayaquil', 'Litigio y práctica procesal.', '', '', '', '', '', '', '', '', 'Abogado', 0, NOW()),

('Ericka Elizabeth Bonilla Salazar', 'ericka.bonilla@bufete.com', '+593998877667', '/uploads/abogados/ericka_carnet.jpg', '/uploads/abogados/ericka_full.jpg', 'Especialista en derecho procesal constitucional.', 'Derecho procesal constitucional', '• Abogada – Universidad Técnica de Machala\n• Magíster en Derecho Procesal Constitucional – UNEMI', 'Experiencia en litigación constitucional y asesoría.', '', '', '', '', '', '', '', '', 'Abogada', 0, NOW()),

('Gustavo Garófalo Bajaña', 'gustavo.garofalo@bufete.com', '+593998877680', '/uploads/abogados/gustavo_carnet.jpg', NULL, 'Estudiante de Derecho y pasante del despacho.', '', '• Estudiante de Derecho – Universidad Tecnológica ECOTEC\n• Pasante', 'Pasantía en apoyo a atención al cliente y trámites legales.', '', '', '', '', '', '', '', '', 'Pasante', 0, NOW());

-- Nota: Ajusta rutas de imagen (`foto_carnet`, `foto_full`) a los archivos reales subidos en /uploads/abogados/.
-- Ejecuta este script sólo después de aplicar la migración `alter_abogados_details.sql`.
